### ISSUE TITLE
ORP value not getting filled

### ISSUE THREAD

**Issue by mruiter** [fpalsson/com.fp.blueconnect#1]
I’m testing the Latest version from GitHub 

Pairing works like a charm 
Values get filled straight away and get updated except the ORP
That value stays empty

tried repair and restart of app a couple of times but never get a value for orp

**Comment by mruiter** [comment]
![F4DF0489-7459-4789-8136-CB1279438D3C](https://user-images.githubusercontent.com/17739535/121414712-40bee980-c967-11eb-8e46-9a4f174fc3b0.png)

**Comment by fpalsson** [comment]
I have added some more logging. Please clone the latest main version and try it out. Send the log after running for a few minutes.

**Comment by mruiter** [comment]
<`About to log in with user: mruiter@tuxweb.nl and pass: *****
{"data":[{"created":"2021-01-27T11:06:25.432Z","blue_device":{"last_hello_message_v":"2021-05-09T11:19:31.000Z","contract_servicePlan":"plus","sleep_state":"awake","fw_version_psoc":"v2.2.3","hw_bundle_extender":false,"contract_isGo":false,"hw_region":"eu","contract_isBasic":false,"sf_rc":"rc1","wake_period":4320,"SN":"32202750164","last_measure_message_ble":"2021-06-04T16:37:49.929Z","sf_rc_country":"NL","hw_type":"plus","fw_version_history":[{"timestamp":"2021-01-27T11:09:22.178Z","fw_version_psoc":"v2.2.3"}],"fs_beacon_enabled":true,"hello_message_cpt":4,"contract_isSwaUs":false,"last_measure_message_sigfox":"2021-06-09T21:06:39.000Z","hw_generation":2,"hw_color":"blue","last_measure_message":"2021-06-09T21:06:39.000Z","production_datetime":"2020-07-08T00:00:00.000Z","serial":"00C275E5","fs_sigfox_enabled":true,"contract_isVpcEligible":true,"location":{"support":"fit50","location":"pipe"},"battery_low":false,"sigfox_geoloc":{"country_name":"Netherlands","country":"528","country_code_iso":"NL","timestamp":"2021-06-09T21:06:39.000Z"}},"user_id":"eu-west-1:de9acbe3-2be4-4287-b39f-214ea039937e","blue_device_serial":"00C275E5","role":"IS_OWNER","swimming_pool_id":"9df2dd82-ae0e-4ca9-9ee2-282469756839"}]}
Blue Riiot API inited succesfully
PoolId: 9df2dd82-ae0e-4ca9-9ee2-282469756839 blueId: 00C275E5
Starting timer
Started timer
[log] 2021-06-09 21:12:21 [ManagerDrivers] [Driver:blue-connect] [Device:00a24bf4-adb9-41a1-8abb-ff6b5aa6a96e] BlueConnectDevice has been initialized
New measurement...
{"status":"OK","last_blue_measure_timestamp":"2021-06-09T18:42:37.000Z","blue_device_serial":"00C275E5","swimming_pool_id":"9df2dd82-ae0e-4ca9-9ee2-282469756839","data":[{"name":"temperature","priority":10,"timestamp":"2021-06-09T18:42:37.000Z","expired":false,"value":24.1,"trend":"undefined","ok_min":30,"ok_max":40,"warning_high":50,"warning_low":5,"gauge_max":50,"gauge_min":0,"issuer":"sigfox"},{"name":"ph","priority":20,"timestamp":"2021-06-09T18:42:37.000Z","expired":false,"value":7.7,"trend":"undefined","ok_min":7.2,"ok_max":7.6,"warning_high":8.4,"warning_low":6.6,"gauge_max":10,"gauge_min":5,"issuer":"sigfox"},{"name":"orp","priority":30,"timestamp":"2021-06-09T18:42:37.000Z","expired":false,"value":359,"trend":"undefined","ok_min":550,"ok_max":650,"warning_high":900,"warning_low":400,"gauge_max":1000,"gauge_min":300,"issuer":"sigfox"},{"name":"conductivity","priority":40,"timestamp":"2021-06-09T18:42:37.000Z","expired":false,"value":1241,"trend":"undefined","ok_min":300,"ok_max":10000,"warning_high":12000,"warning_low":200,"gauge_max":20000,"gauge_min":0,"issuer":"sigfox"}]}
New temperature measurement. Now: 24.1
New pH measurement. Now: 7.7
New ORP measurement. Now: 359
New conductivity measurement. Now: 1241
(node:31298) UnhandledPromiseRejectionWarning: Error: measure_orp OutOfRangeError: 359 is smaller than 1000 (out_of_range)
    at Remote Process

(node:31298) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31298) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
New measurement...
{"status":"OK","last_blue_measure_timestamp":"2021-06-09T18:42:37.000Z","blue_device_serial":"00C275E5","swimming_pool_id":"9df2dd82-ae0e-4ca9-9ee2-282469756839","data":[{"name":"temperature","priority":10,"timestamp":"2021-06-09T18:42:37.000Z","expired":false,"value":24.1,"trend":"undefined","ok_min":30,"ok_max":40,"warning_high":50,"warning_low":5,"gauge_max":50,"gauge_min":0,"issuer":"sigfox"},{"name":"ph","priority":20,"timestamp":"2021-06-09T18:42:37.000Z","expired":false,"value":7.7,"trend":"undefined","ok_min":7.2,"ok_max":7.6,"warning_high":8.4,"warning_low":6.6,"gauge_max":10,"gauge_min":5,"issuer":"sigfox"},{"name":"orp","priority":30,"timestamp":"2021-06-09T18:42:37.000Z","expired":false,"value":359,"trend":"undefined","ok_min":550,"ok_max":650,"warning_high":900,"warning_low":400,"gauge_max":1000,"gauge_min":300,"issuer":"sigfox"},{"name":"conductivity","priority":40,"timestamp":"2021-06-09T18:42:37.000Z","expired":false,"value":1241,"trend":"undefined","ok_min":300,"ok_max":10000,"warning_high":12000,"warning_low":200,"gauge_max":20000,"gauge_min":0,"issuer":"sigfox"}]}`>

**Comment by fpalsson** [comment]
Ahhh. Your pool is too dirty to be handled by my app. You should add some Cl, :-)

ORP value was so low it was outside the range I had set for that value. That is now corrected, and pushed to master. 

Retreive the last changes and rebuild. 

Thanks for this finding. I hope you have a plesant swim after adding the chlorine :-)

**Comment by mruiter** [comment]
No need , it’s just below recommend. I do hydrolysis . That’s the lowest chlorine value you can have 😉 it’s crystal clear you can use it as drinking water 

Verstuurd vanaf mijn iPhone

**Comment by mruiter** [comment]
To give you an idea . Optimal value for ORP with hydrolysis for my pool is 410
Well below the 1000 I see in the error 😅


Verstuurd vanaf mijn iPhone

**Comment by fpalsson** [comment]
Aha. 

Regarding the 1000 shown in the error that seems to be a bug at Athoms end. I do belive they mix up min and max.

Did you have a chance to test the corrected version?

**Comment by mruiter** [comment]
Confirmed working with the latest github version. Thx !!!!!!
BTW Great you made the app

**Comment by fpalsson** [comment]
> Confirmed working with the latest github version. Thx !!!!!!
> BTW Great you made the app

Thanks!
