### ISSUE TITLE
Implementation of the Feed parsing

### ISSUE THREAD

**Issue by mruiter** [fpalsson/com.fp.blueconnect#2]
It would be handy to have a way to parse the feed.

Just as example the tags      

AddPH+
AddPH-
AddCl

So we can parse these values in flows to automate the adding of the chemicals for excellent water quality

**Comment by fpalsson** [comment]
I was thinking of these mechanisms:
1. Having an alarm (boolean value) as a summary for "Pool needs attention". Of cause a flow trigger for this as well.
2. Adding flow triggers for "pH goes below recommended level". Of cause the same for "... goes above...". And also the same for ORP and conductivity. 
3. Point 2 probably calls for a "pH back within recommended levels"-trigger.
4.  Also flow triggers for "pH value changed" and "pH value goes above/below". The same for ORP and conductivity.

Would that be sufficient?

**Comment by mruiter** [comment]
the feed also gives the value of how many grams needs to be added
this is for both my pools always around right amount to get it all into perfect vaulues
so pasing the text to grap the advise on how many grams need to be added so one can time the cl or ph pumps would be nice to have also 

Verstuurd vanaf mijn iPad

**Comment by fpalsson** [comment]
Check out https://github.com/fpalsson/com.fp.blueconnect/wiki/Todo-list for my upcoming plans. Please comment on them here if you feel like it.

**Comment by mruiter** [comment]
Will do and will close this issue since its a todo and not a real issue
